// frontend-react-app/src/components/RakutenBankCard.tsx
import { type FC } from 'react';
import BaseCard from './BaseCard';

interface RakutenBankCardProps {
  total: number;
  loading: boolean;
  onClickUpdate: () => void;
}

export const RakutenBankCard: FC<RakutenBankCardProps> = ({ total, loading, onClickUpdate }) => {
  return (
    <BaseCard
      title="楽天銀行"
      bgColor="#bf0000"
      total={total}
      loading={loading}
      onClickUpdate={onClickUpdate}
    />
  );
};

export default RakutenBankCard;

// frontend/src/components/RakutenBankCard.vue
<template>
  <BaseCard
    title="楽天銀行"
    :total="total"
    :loading="loading"
    bgColor="#bf0000"
    @click-update="handleClick"
  />
</template>

<script setup lang="ts">
import BaseCard from "components/BaseCard.vue";

defineProps<{
  total: number;
  loading: boolean;
}>();

const emits = defineEmits<{
  (e: "click-update"): void;
}>();

const handleClick = () => {
  emits("click-update");
};
</script>
