// frontend/src/components/SbiShinseiBankCard.tsx
import { type FC } from 'react';
import BaseCard from './BaseCard';

interface SbiShinseiBankCardProps {
  total: number;
  loading: boolean;
  onClickUpdate: () => void;
}

export const SbiShinseiBankCard: FC<SbiShinseiBankCardProps> = ({ total, loading, onClickUpdate }) => {
  return (
    <BaseCard
      title="SBI新生銀行"
      bgColor="#e8f1f9"
      total={total}
      loading={loading}
      onClickUpdate={onClickUpdate}
    />
  );
};

export default SbiShinseiBankCard;

// frontend/src/components/SbiShinseiBankCard.vue
<template>
  <BaseCard
    title="SBI新生銀行"
    :total="total"
    :loading="loading"
    bgColor="#e8f1f9"
    @click-update="handleClick"
  />
</template>

<script setup lang="ts">
import BaseCard from "components/BaseCard.vue";

defineProps<{
  total: number;
  loading: boolean;
}>();

const emits = defineEmits<{
  (e: "click-update"): void;
}>();

const handleClick = () => {
  emits("click-update");
};
</script>
