// frontend-react-app/src/components/SumishinSbiBankCard.tsx
import { type FC } from 'react';
import BaseCard from './BaseCard';

interface SumishinSbiBankCardProps {
  total: number;
  loading: boolean;
  onClickUpdate: () => void;
}

export const SumishinSbiBankCard: FC<SumishinSbiBankCardProps> = ({ total, loading, onClickUpdate }) => {
  return (
    <BaseCard
      title="住信SBI銀行"
      bgColor="#0058A0"
      total={total}
      loading={loading}
      onClickUpdate={onClickUpdate}
    />
  );
};

export default SumishinSbiBankCard;

// frontend/src/components/SumishinSbiBankCard.vue
<template>
  <BaseCard
    title="住信SBI銀行"
    :total="total"
    :loading="loading"
    bgColor="#0058A0"
    @click-update="handleClick"
  />
</template>

<script setup lang="ts">
import BaseCard from "components/BaseCard.vue";

defineProps<{
  total: number;
  loading: boolean;
}>();

const emits = defineEmits<{
  (e: "click-update"): void;
}>();

const handleClick = () => {
  emits("click-update");
};
</script>
