// frontend/src/components/TotalCard.vue
<template>
  <BaseCard
    title="Total"
    :total="total"
    :loading="loading"
    bgColor="black"
    @click-update="handleClick"
  />
</template>

<script setup lang="ts">
import BaseCard from "components/BaseCard.vue";

defineProps<{
  total: number;
  loading: boolean;
}>();

const emits = defineEmits<{
  (e: "click-update"): void;
}>();

const handleClick = () => {
  emits("click-update");
};
</script>

// frontend/src/components/TotalCard.tsx
import { type FC } from 'react';
import BaseCard from './BaseCard';

interface TotalCardProps {
  total: number;
  loading: boolean;
  onClickUpdate: () => void;
}

export const TotalCard: FC<TotalCardProps> = ({ total, loading, onClickUpdate }) => {
  return (
    <BaseCard
      title="Total"
      bgColor="black"
      total={total}
      loading={loading}
      onClickUpdate={onClickUpdate}
    />
  );
};

export default TotalCard;
