// frontend/src/components/MitsuisumitomoCardCard.vue
<template>
  <BaseCard
    title="三井住友カード"
    :total="total"
    :loading="loading"
    bgColor="#004736"
    @click-update="handleClick"
  />
</template>

<script setup lang="ts">
import BaseCard from "components/BaseCard.vue";

defineProps<{
  total: number;
  loading: boolean;
}>();

const emits = defineEmits<{
  (e: "click-update"): void;
}>();

const handleClick = () => {
  emits("click-update");
};
</script>

// frontend-react/frontend-react-app/src/components/MitsuisumitomoCardCard.tsx
import React from 'react';
import BaseCard from './BaseCard';

interface MitsuisumitomoCardCardProps {
  total: number;
  loading: boolean;
  onClickUpdate: () => void;
}

const MitsuisumitomoCardCard: React.FC<MitsuisumitomoCardCardProps> = ({ total, loading, onClickUpdate }) => {
  return (
    <BaseCard
      title="三井住友カード"
      bgColor="#004736"
      total={total}
      loading={loading}
      onClickUpdate={onClickUpdate}
    />
  );
};

export default MitsuisumitomoCardCard;
