// frontend/src/components/SbiBenefitSystemCard.vue
<template>
  <BaseCard
    title="SBIベネフィットシステムズ"
    :total="total"
    :loading="loading"
    bgColor="#2ea2ed"
    @click-update="handleClick"
  />
</template>

<script setup lang="ts">
import BaseCard from "components/BaseCard.vue";

defineProps<{
  total: number;
  loading: boolean;
}>();

const emits = defineEmits<{
  (e: "click-update"): void;
}>();

const handleClick = () => {
  emits("click-update");
};
</script>

// frontend-react/frontend-react-app/src/components/SbiBenefitSystemCard.tsx
import React from 'react';
import BaseCard from './BaseCard';

interface SbiBenefitSystemCardProps {
  total: number;
  loading: boolean;
  onClickUpdate: () => void;
}

const SbiBenefitSystemCard: React.FC<SbiBenefitSystemCardProps> = ({ total, loading, onClickUpdate }) => {
  return (
    <BaseCard
      title="SBIベネフィットシステムズ"
      bgColor="#2ea2ed"
      total={total}
      loading={loading}
      onClickUpdate={onClickUpdate}
    />
  );
};

export default SbiBenefitSystemCard;
